/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_EXTERNAL_ID_VALUE` (
  `ID_STATEMENT` bigint(20) NOT NULL,
  `VALUE_EXTERNAL_ID` varchar(1200) NOT NULL,
  `VALUE_EXTERNAL_ID_NORMALIZED` varchar(1200) DEFAULT NULL,
  `FORMATTER_URL` text DEFAULT NULL,
  `FORMATTER_URI_RDF` text DEFAULT NULL,
  `VALIDATION_STATUS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_EXTERNAL_ID_VALUE_NORMALIZED` (`VALUE_EXTERNAL_ID_NORMALIZED`(255)),
  KEY `IDX_T_WC_WIKIDATA_EXTERNAL_ID_VALUE_STATUS` (`VALIDATION_STATUS`),
  CONSTRAINT `FK_T_WC_WIKIDATA_EXTERNAL_ID_VALUE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER BI_T_WC_WIKIDATA_EXTERNAL_ID_VALUE BEFORE INSERT ON T_WC_WIKIDATA_EXTERNAL_ID_VALUE
FOR EACH ROW
BEGIN
  DECLARE v_value_type VARCHAR(50);
  SELECT VALUE_TYPE INTO v_value_type FROM T_WC_WIKIDATA_STATEMENT WHERE ID_STATEMENT=NEW.ID_STATEMENT LIMIT 1;
  IF v_value_type IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='EXTERNAL_ID_VALUE: parent statement not found'; END IF;
  IF v_value_type <> 'external_id' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='EXTERNAL_ID_VALUE: parent VALUE_TYPE must be external_id'; END IF;
  IF EXISTS (SELECT 1 FROM T_WC_WIKIDATA_ITEM_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_STRING_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_MEDIA_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_TIME_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_QUANTITY_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT)
  THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='EXTERNAL_ID_VALUE: statement already exists in another child table'; END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_ITEM` (
  `ID_ROW` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `LABEL_EN` varchar(500) DEFAULT NULL,
  `DESCRIPTION_EN` text DEFAULT NULL,
  `LABELS_JSON` longtext DEFAULT NULL,
  `DESCRIPTIONS_JSON` longtext DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_ROW`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_ITEM_ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_ITEM_LABEL_EN` (`LABEL_EN`(255)),
  KEY `IDX_T_WC_WIKIDATA_ITEM_DELETED` (`DELETED`)
) ENGINE=InnoDB AUTO_INCREMENT=1187823 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_ITEM_PROPERTY` (
  `ID_ROW` int(11) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `ID_PROPERTY` varchar(50) NOT NULL,
  `ID_ITEM` varchar(50) DEFAULT NULL,
  `DELETED` int(5) DEFAULT NULL,
  `DISPLAY_ORDER` int(5) DEFAULT NULL,
  `ID_CREATOR` int(5) DEFAULT NULL,
  `DAT_CREAT` date DEFAULT NULL,
  `ID_OWNER` int(5) DEFAULT NULL,
  `TIM_UPDATED` datetime DEFAULT NULL,
  `ID_USER_UPDATED` int(5) DEFAULT NULL,
  PRIMARY KEY (`ID_ROW`),
  KEY `DELETED` (`DELETED`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `ID_OWNER` (`ID_OWNER`),
  KEY `ID_CREATOR` (`ID_CREATOR`),
  KEY `ID_USER_UPDATED` (`ID_USER_UPDATED`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `ID_PROPERTY` (`ID_PROPERTY`),
  KEY `ID_ITEM` (`ID_ITEM`)
) ENGINE=InnoDB AUTO_INCREMENT=7162305 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_ITEM_V1` (
  `ID_ROW` int(11) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `LANG` varchar(10) DEFAULT NULL,
  `LABEL` varchar(250) DEFAULT NULL,
  `ALIASES` mediumtext DEFAULT NULL,
  `DESCRIPTION` mediumtext DEFAULT NULL,
  `DELETED` int(5) DEFAULT NULL,
  `DISPLAY_ORDER` int(5) DEFAULT NULL,
  `ID_CREATOR` int(5) DEFAULT NULL,
  `DAT_CREAT` date DEFAULT NULL,
  `ID_OWNER` int(5) DEFAULT NULL,
  `TIM_UPDATED` datetime DEFAULT NULL,
  `ID_USER_UPDATED` int(5) DEFAULT NULL,
  `INSTANCE_OF` varchar(50) DEFAULT NULL,
  `WIKIPEDIA_IMAGE_PATH` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_ROW`),
  KEY `DELETED` (`DELETED`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `ID_OWNER` (`ID_OWNER`),
  KEY `ID_CREATOR` (`ID_CREATOR`),
  KEY `ID_USER_UPDATED` (`ID_USER_UPDATED`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `LABEL` (`LABEL`),
  KEY `DESCRIPTION` (`DESCRIPTION`(768)),
  KEY `LANG` (`LANG`),
  KEY `ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `INSTANCE_OF` (`INSTANCE_OF`),
  KEY `WIKIPEDIA_IMAGE_PATH` (`WIKIPEDIA_IMAGE_PATH`)
) ENGINE=InnoDB AUTO_INCREMENT=917979 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_ITEM_VALUE` (
  `ID_STATEMENT` bigint(20) NOT NULL,
  `ID_ITEM` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_ITEM_VALUE_ID_ITEM` (`ID_ITEM`),
  KEY `IDX_T_WC_WIKIDATA_ITEM_VALUE_STATEMENT_ITEM` (`ID_STATEMENT`,`ID_ITEM`),
  CONSTRAINT `FK_T_WC_WIKIDATA_ITEM_VALUE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER BI_T_WC_WIKIDATA_ITEM_VALUE BEFORE INSERT ON T_WC_WIKIDATA_ITEM_VALUE
FOR EACH ROW
BEGIN
  DECLARE v_value_type VARCHAR(50);
  SELECT VALUE_TYPE INTO v_value_type FROM T_WC_WIKIDATA_STATEMENT WHERE ID_STATEMENT=NEW.ID_STATEMENT LIMIT 1;
  IF v_value_type IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='ITEM_VALUE: parent statement not found'; END IF;
  IF v_value_type <> 'item' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='ITEM_VALUE: parent VALUE_TYPE must be item'; END IF;
  IF EXISTS (SELECT 1 FROM T_WC_WIKIDATA_STRING_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_MEDIA_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_TIME_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_QUANTITY_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT)
  THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='ITEM_VALUE: statement already exists in another child table'; END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_MEDIA_RESOURCE` (
  `ID_MEDIA_RESOURCE` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_STATEMENT` bigint(20) NOT NULL,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `ID_PROPERTY` varchar(50) NOT NULL,
  `SOURCE_PLATFORM` enum('commons','internet_archive','youtube') NOT NULL,
  `SOURCE_IDENTIFIER` varchar(1000) NOT NULL,
  `SOURCE_IDENTIFIER_NORMALIZED` varchar(1000) DEFAULT NULL,
  `RESOURCE_KEY` varchar(1200) DEFAULT NULL,
  `RESOURCE_KIND` enum('video','audio','image','document') NOT NULL DEFAULT 'video',
  `CONTENT_ROLE` enum('full','trailer','excerpt','clip','interview','unknown') NOT NULL DEFAULT 'unknown',
  `CONTENT_SCOPE` enum('main_work','related_material','promotional','archival','unknown') NOT NULL DEFAULT 'unknown',
  `LANG_CODE` varchar(20) DEFAULT NULL,
  `IS_PREFERRED_RESOURCE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_PRIMARY_FOR_ENTITY` tinyint(1) NOT NULL DEFAULT 0,
  `SOURCE_PRIORITY` int(11) DEFAULT NULL,
  `QUALITY_SCORE` decimal(10,4) DEFAULT NULL,
  `RESOURCE_TITLE` varchar(1000) DEFAULT NULL,
  `RESOURCE_SUBTITLE` varchar(1000) DEFAULT NULL,
  `RESOURCE_DESCRIPTION` text DEFAULT NULL,
  `CHANNEL_OR_COLLECTION` varchar(1000) DEFAULT NULL,
  `THUMBNAIL_URL_PRIMARY` text DEFAULT NULL,
  `DURATION_SECONDS` int(11) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  `MIME_TYPE_PRIMARY` varchar(255) DEFAULT NULL,
  `FILE_EXTENSION_PRIMARY` varchar(50) DEFAULT NULL,
  `FILE_SIZE_PRIMARY` bigint(20) DEFAULT NULL,
  `IS_PLAYABLE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_DOWNLOADABLE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_EMBEDDABLE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `IS_VALID` tinyint(1) DEFAULT NULL,
  `RESOLUTION_STATUS` enum('resolved','partial','failed','pending','obsolete') NOT NULL DEFAULT 'pending',
  `RESOLUTION_METHOD` varchar(100) DEFAULT NULL,
  `LAST_RESOLVED_AT` datetime DEFAULT NULL,
  `LAST_CHECKED_AT` datetime DEFAULT NULL,
  `LAST_SUCCESS_AT` datetime DEFAULT NULL,
  `ERROR_CODE` varchar(100) DEFAULT NULL,
  `ERROR_MESSAGE` text DEFAULT NULL,
  `IMPORT_BATCH_ID` varchar(100) DEFAULT NULL,
  `DISCOVERED_AT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `ID_USER_UPDATED` bigint(20) DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ID_MEDIA_RESOURCE`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_MEDIA_RESOURCE_STATEMENT_PLATFORM_IDENTIFIER` (`ID_STATEMENT`,`SOURCE_PLATFORM`,`SOURCE_IDENTIFIER_NORMALIZED`(255)),
  UNIQUE KEY `UK_T_WC_WIKIDATA_MEDIA_RESOURCE_RESOURCE_KEY` (`RESOURCE_KEY`(255)),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ID_STATEMENT` (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ID_PROPERTY` (`ID_PROPERTY`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_PLATFORM` (`SOURCE_PLATFORM`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ROLE` (`CONTENT_ROLE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_STATUS` (`RESOLUTION_STATUS`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_PREFERRED` (`IS_PREFERRED_RESOURCE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_PRIMARY_ENTITY` (`IS_PRIMARY_FOR_ENTITY`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ACTIVE` (`IS_ACTIVE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_VALID` (`IS_VALID`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_DELETED` (`DELETED`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_ENTITY_PLATFORM` (`ID_WIKIDATA`,`SOURCE_PLATFORM`),
  CONSTRAINT `FK_T_WC_WIKIDATA_MEDIA_RESOURCE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK` (
  `ID_MEDIA_RESOURCE_CHECK` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_MEDIA_RESOURCE` bigint(20) NOT NULL,
  `ID_MEDIA_RESOURCE_URL` bigint(20) DEFAULT NULL,
  `CHECK_SCOPE` enum('resource','url') NOT NULL,
  `CHECK_TYPE` enum('resolve','api_lookup','http_head','http_get','redirect_trace','playability_check','embed_check','metadata_refresh') NOT NULL,
  `CHECK_REASON` varchar(100) DEFAULT NULL,
  `CHECK_STATUS` enum('success','partial','failure') NOT NULL,
  `RESULT_CODE` varchar(100) DEFAULT NULL,
  `RESULT_SUMMARY` varchar(1000) DEFAULT NULL,
  `HTTP_STATUS` int(11) DEFAULT NULL,
  `CONTENT_TYPE_HEADER` varchar(255) DEFAULT NULL,
  `REDIRECT_URL` text DEFAULT NULL,
  `RESPONSE_TIME_MS` int(11) DEFAULT NULL,
  `OBSERVED_URL` text DEFAULT NULL,
  `OBSERVED_MIME_TYPE` varchar(255) DEFAULT NULL,
  `OBSERVED_FILE_SIZE` bigint(20) DEFAULT NULL,
  `OBSERVED_DURATION_SECONDS` int(11) DEFAULT NULL,
  `OBSERVED_WIDTH` int(11) DEFAULT NULL,
  `OBSERVED_HEIGHT` int(11) DEFAULT NULL,
  `ERROR_CODE` varchar(100) DEFAULT NULL,
  `ERROR_MESSAGE` text DEFAULT NULL,
  `RAW_RESPONSE_SNIPPET` text DEFAULT NULL,
  `CHECKED_AT` datetime NOT NULL DEFAULT current_timestamp(),
  `CHECKER_NAME` varchar(100) DEFAULT NULL,
  `IMPORT_BATCH_ID` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_MEDIA_RESOURCE_CHECK`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE` (`ID_MEDIA_RESOURCE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE_URL` (`ID_MEDIA_RESOURCE_URL`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_SCOPE` (`CHECK_SCOPE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_TYPE` (`CHECK_TYPE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_STATUS` (`CHECK_STATUS`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_HTTP_STATUS` (`HTTP_STATUS`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_CHECKED_AT` (`CHECKED_AT`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_IMPORT_BATCH_ID` (`IMPORT_BATCH_ID`),
  CONSTRAINT `FK_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE` FOREIGN KEY (`ID_MEDIA_RESOURCE`) REFERENCES `T_WC_WIKIDATA_MEDIA_RESOURCE` (`ID_MEDIA_RESOURCE`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_T_WC_WIKIDATA_MEDIA_RESOURCE_CHECK_RESOURCE_URL` FOREIGN KEY (`ID_MEDIA_RESOURCE_URL`) REFERENCES `T_WC_WIKIDATA_MEDIA_RESOURCE_URL` (`ID_MEDIA_RESOURCE_URL`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_MEDIA_RESOURCE_URL` (
  `ID_MEDIA_RESOURCE_URL` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_MEDIA_RESOURCE` bigint(20) NOT NULL,
  `URL_TYPE` enum('page','watch','embed','file','thumbnail','metadata','manifest','subtitle','transcript') NOT NULL,
  `URL_ROLE` varchar(100) DEFAULT NULL,
  `DISPLAY_ORDER` int(11) DEFAULT NULL,
  `IS_CANONICAL` tinyint(1) NOT NULL DEFAULT 0,
  `IS_PREFERRED` tinyint(1) NOT NULL DEFAULT 0,
  `IS_DIRECT_FILE` tinyint(1) NOT NULL DEFAULT 0,
  `URL` text NOT NULL,
  `URL_NORMALIZED` text DEFAULT NULL,
  `URL_HASH` char(64) DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `FILE_EXTENSION` varchar(50) DEFAULT NULL,
  `FILE_SIZE` bigint(20) DEFAULT NULL,
  `WIDTH` int(11) DEFAULT NULL,
  `HEIGHT` int(11) DEFAULT NULL,
  `BITRATE` int(11) DEFAULT NULL,
  `FRAME_RATE` decimal(10,4) DEFAULT NULL,
  `VIDEO_CODEC` varchar(255) DEFAULT NULL,
  `AUDIO_CODEC` varchar(255) DEFAULT NULL,
  `DURATION_SECONDS` int(11) DEFAULT NULL,
  `QUALITY_LABEL` varchar(100) DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `IS_PLAYABLE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_DOWNLOADABLE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_EMBEDDABLE` tinyint(1) NOT NULL DEFAULT 0,
  `IS_PUBLIC` tinyint(1) DEFAULT NULL,
  `HTTP_STATUS` int(11) DEFAULT NULL,
  `CONTENT_TYPE_HEADER` varchar(255) DEFAULT NULL,
  `REDIRECT_URL` text DEFAULT NULL,
  `LAST_CHECKED_AT` datetime DEFAULT NULL,
  `LAST_SUCCESS_AT` datetime DEFAULT NULL,
  `CHECK_COUNT` int(11) NOT NULL DEFAULT 0,
  `FAIL_COUNT` int(11) NOT NULL DEFAULT 0,
  `ERROR_CODE` varchar(100) DEFAULT NULL,
  `ERROR_MESSAGE` text DEFAULT NULL,
  `DISCOVERED_AT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `DELETED` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`ID_MEDIA_RESOURCE_URL`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_RESOURCE_HASH` (`ID_MEDIA_RESOURCE`,`URL_HASH`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_RESOURCE` (`ID_MEDIA_RESOURCE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_TYPE` (`URL_TYPE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_PREFERRED` (`IS_PREFERRED`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_CANONICAL` (`IS_CANONICAL`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_DIRECT_FILE` (`IS_DIRECT_FILE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_ACTIVE` (`IS_ACTIVE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_PLAYABLE` (`IS_PLAYABLE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_DOWNLOADABLE` (`IS_DOWNLOADABLE`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_HTTP_STATUS` (`HTTP_STATUS`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_QUALITY_LABEL` (`QUALITY_LABEL`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_DELETED` (`DELETED`),
  CONSTRAINT `FK_T_WC_WIKIDATA_MEDIA_RESOURCE_URL_RESOURCE` FOREIGN KEY (`ID_MEDIA_RESOURCE`) REFERENCES `T_WC_WIKIDATA_MEDIA_RESOURCE` (`ID_MEDIA_RESOURCE`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_MEDIA_VALUE` (
  `ID_STATEMENT` bigint(20) NOT NULL,
  `FILE_NAME` varchar(1000) NOT NULL,
  `MEDIA_REPOSITORY` varchar(100) DEFAULT NULL,
  `FILE_PAGE_URL` text DEFAULT NULL,
  `FILE_DIRECT_URL` text DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `FILE_EXTENSION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_VALUE_FILE_NAME` (`FILE_NAME`(255)),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_VALUE_MEDIA_REPOSITORY` (`MEDIA_REPOSITORY`),
  KEY `IDX_T_WC_WIKIDATA_MEDIA_VALUE_MIME_TYPE` (`MIME_TYPE`),
  CONSTRAINT `FK_T_WC_WIKIDATA_MEDIA_VALUE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER BI_T_WC_WIKIDATA_MEDIA_VALUE BEFORE INSERT ON T_WC_WIKIDATA_MEDIA_VALUE
FOR EACH ROW
BEGIN
  DECLARE v_value_type VARCHAR(50);
  SELECT VALUE_TYPE INTO v_value_type FROM T_WC_WIKIDATA_STATEMENT WHERE ID_STATEMENT=NEW.ID_STATEMENT LIMIT 1;
  IF v_value_type IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='MEDIA_VALUE: parent statement not found'; END IF;
  IF v_value_type <> 'media' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='MEDIA_VALUE: parent VALUE_TYPE must be media'; END IF;
  IF EXISTS (SELECT 1 FROM T_WC_WIKIDATA_ITEM_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_STRING_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_TIME_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_QUANTITY_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT)
  THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='MEDIA_VALUE: statement already exists in another child table'; END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_MOVIE` (
  `ID_ROW` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `LABEL_EN` varchar(500) DEFAULT NULL,
  `DESCRIPTION_EN` text DEFAULT NULL,
  `LABELS_JSON` longtext DEFAULT NULL,
  `DESCRIPTIONS_JSON` longtext DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_ROW`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_MOVIE_ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_MOVIE_LABEL_EN` (`LABEL_EN`(255)),
  KEY `IDX_T_WC_WIKIDATA_MOVIE_DELETED` (`DELETED`)
) ENGINE=InnoDB AUTO_INCREMENT=790517 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_MOVIE_V1` (
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `ID_MOVIE` int(11) NOT NULL,
  `TITLE` varchar(250) DEFAULT NULL,
  `DAT_RELEASE` date DEFAULT NULL,
  `ID_IMDB` varchar(20) DEFAULT NULL,
  `ALIASES` mediumtext DEFAULT NULL,
  `DELETED` int(5) DEFAULT NULL,
  `DISPLAY_ORDER` int(5) DEFAULT NULL,
  `ID_CREATOR` int(5) DEFAULT NULL,
  `DAT_CREAT` date DEFAULT NULL,
  `ID_OWNER` int(5) DEFAULT NULL,
  `TIM_UPDATED` datetime DEFAULT NULL,
  `ID_USER_UPDATED` int(5) DEFAULT NULL,
  `CRAWLER_VERSION` int(5) DEFAULT NULL,
  `PLEX_MEDIA_KEY` varchar(50) DEFAULT NULL,
  `ID_CRITERION` int(11) DEFAULT NULL,
  `ID_CRITERION_SPINE` int(11) DEFAULT NULL,
  `INSTANCE_OF` varchar(50) DEFAULT NULL,
  `WIKIPEDIA_POSTER_PATH` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_WIKIDATA`),
  KEY `DELETED` (`DELETED`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `ID_OWNER` (`ID_OWNER`),
  KEY `ID_CREATOR` (`ID_CREATOR`),
  KEY `ID_USER_UPDATED` (`ID_USER_UPDATED`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `ID_IMDB` (`ID_IMDB`),
  KEY `TITLE` (`TITLE`),
  KEY `DAT_RELEASE` (`DAT_RELEASE`),
  KEY `CRAWLER_VERSION` (`CRAWLER_VERSION`),
  KEY `ID_MOVIE` (`ID_MOVIE`),
  KEY `ID_CRITERION` (`ID_CRITERION`),
  KEY `ID_CRITERION_SPINE` (`ID_CRITERION_SPINE`),
  KEY `PLEX_MEDIA_KEY` (`PLEX_MEDIA_KEY`),
  KEY `INSTANCE_OF` (`INSTANCE_OF`),
  KEY `WIKIPEDIA_POSTER_PATH` (`WIKIPEDIA_POSTER_PATH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_PERSON` (
  `ID_ROW` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `LABEL_EN` varchar(500) DEFAULT NULL,
  `DESCRIPTION_EN` text DEFAULT NULL,
  `LABELS_JSON` longtext DEFAULT NULL,
  `DESCRIPTIONS_JSON` longtext DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_ROW`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_PERSON_ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_PERSON_LABEL_EN` (`LABEL_EN`(255)),
  KEY `IDX_T_WC_WIKIDATA_PERSON_DELETED` (`DELETED`)
) ENGINE=InnoDB AUTO_INCREMENT=1581033 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_PERSON_V1` (
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `ID_PERSON` int(11) DEFAULT NULL,
  `NAME` varchar(200) DEFAULT NULL,
  `ID_IMDB` varchar(20) DEFAULT NULL,
  `BIRTHDAY` datetime DEFAULT NULL,
  `DEATHDAY` datetime DEFAULT NULL,
  `ALIASES` mediumtext DEFAULT NULL,
  `DELETED` int(5) DEFAULT NULL,
  `DISPLAY_ORDER` int(5) DEFAULT NULL,
  `ID_CREATOR` int(5) DEFAULT NULL,
  `DAT_CREAT` date DEFAULT NULL,
  `ID_OWNER` int(5) DEFAULT NULL,
  `TIM_UPDATED` datetime DEFAULT NULL,
  `ID_USER_UPDATED` int(5) DEFAULT NULL,
  `CRAWLER_VERSION` int(5) DEFAULT NULL,
  `INSTANCE_OF` varchar(50) DEFAULT NULL,
  `WIKIPEDIA_PROFILE_PATH` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_WIKIDATA`),
  KEY `DELETED` (`DELETED`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `ID_OWNER` (`ID_OWNER`),
  KEY `ID_CREATOR` (`ID_CREATOR`),
  KEY `ID_USER_UPDATED` (`ID_USER_UPDATED`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `ID_IMDB` (`ID_IMDB`),
  KEY `BIRTHDAY` (`BIRTHDAY`),
  KEY `DEATHDAY` (`DEATHDAY`),
  KEY `NAME` (`NAME`),
  KEY `CRAWLER_VERSION` (`CRAWLER_VERSION`),
  KEY `ID_PERSON` (`ID_PERSON`),
  KEY `INSTANCE_OF` (`INSTANCE_OF`),
  KEY `ALIASES` (`ALIASES`(768)),
  KEY `WIKIPEDIA_PROFILE_PATH` (`WIKIPEDIA_PROFILE_PATH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_PROPERTY` (
  `ID_PROPERTY` varchar(50) NOT NULL,
  `LABEL` varchar(250) DEFAULT NULL,
  `DESCRIPTION` mediumtext DEFAULT NULL,
  `DELETED` int(5) DEFAULT NULL,
  `DISPLAY_ORDER` int(5) DEFAULT NULL,
  `ID_CREATOR` int(5) DEFAULT NULL,
  `DAT_CREAT` date DEFAULT NULL,
  `ID_OWNER` int(5) DEFAULT NULL,
  `TIM_UPDATED` datetime DEFAULT NULL,
  `ID_USER_UPDATED` int(5) DEFAULT NULL,
  PRIMARY KEY (`ID_PROPERTY`),
  KEY `DELETED` (`DELETED`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `ID_OWNER` (`ID_OWNER`),
  KEY `ID_CREATOR` (`ID_CREATOR`),
  KEY `ID_USER_UPDATED` (`ID_USER_UPDATED`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `LABEL` (`LABEL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_PROPERTY_METADATA` (
  `ID_ROW` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_PROPERTY` varchar(50) NOT NULL,
  `PROPERTY_LABEL` varchar(500) DEFAULT NULL,
  `PROPERTY_DESCRIPTION` text DEFAULT NULL,
  `WIKIDATA_DATATYPE` varchar(100) DEFAULT NULL,
  `LOCAL_VALUE_TYPE` enum('item','string','external_id','media','time','quantity') DEFAULT NULL,
  `EXPECTED_CHILD_TABLE` varchar(100) DEFAULT NULL,
  `FORMATTER_URL` text DEFAULT NULL,
  `FORMATTER_URI_FOR_RDF` text DEFAULT NULL,
  `IS_SUPPORTED` tinyint(1) NOT NULL DEFAULT 1,
  `IS_ACTIVE` tinyint(1) NOT NULL DEFAULT 1,
  `LAST_SYNC_AT` datetime DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_ROW`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_PROPERTY_METADATA_ID_PROPERTY` (`ID_PROPERTY`),
  KEY `IDX_T_WC_WIKIDATA_PROPERTY_METADATA_LOCAL_VALUE_TYPE` (`LOCAL_VALUE_TYPE`),
  KEY `IDX_T_WC_WIKIDATA_PROPERTY_METADATA_WIKIDATA_DATATYPE` (`WIKIDATA_DATATYPE`),
  KEY `IDX_T_WC_WIKIDATA_PROPERTY_METADATA_IS_SUPPORTED` (`IS_SUPPORTED`),
  KEY `IDX_T_WC_WIKIDATA_PROPERTY_METADATA_IS_ACTIVE` (`IS_ACTIVE`),
  KEY `IDX_T_WC_WIKIDATA_PROPERTY_METADATA_DELETED` (`DELETED`)
) ENGINE=InnoDB AUTO_INCREMENT=33023 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL,
  `VALUE_EXTERNAL_ID` varchar(1000) NOT NULL,
  `VALUE_EXTERNAL_ID_NORMALIZED` varchar(1000) DEFAULT NULL,
  `FORMATTER_URL` text DEFAULT NULL,
  `FORMATTER_URI_RDF` text DEFAULT NULL,
  `VALIDATION_STATUS` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  KEY `IDX_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE_NORMALIZED` (`VALUE_EXTERNAL_ID_NORMALIZED`(255)),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUALIFIER_EXTERNAL_ID_VALUE_PARENT` FOREIGN KEY (`ID_STATEMENT_QUALIFIER`) REFERENCES `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (`ID_STATEMENT_QUALIFIER`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUALIFIER_ITEM_VALUE` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL,
  `ID_ITEM` varchar(50) NOT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  KEY `IDX_T_WC_WIKIDATA_QUAL_ITEM_VALUE_ITEM` (`ID_ITEM`),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUAL_ITEM_VALUE_PARENT` FOREIGN KEY (`ID_STATEMENT_QUALIFIER`) REFERENCES `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (`ID_STATEMENT_QUALIFIER`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL,
  `FILE_NAME` varchar(1000) NOT NULL,
  `MEDIA_REPOSITORY` varchar(100) DEFAULT NULL,
  `FILE_PAGE_URL` text DEFAULT NULL,
  `FILE_DIRECT_URL` text DEFAULT NULL,
  `MIME_TYPE` varchar(255) DEFAULT NULL,
  `FILE_EXTENSION` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUALIFIER_MEDIA_VALUE_PARENT` FOREIGN KEY (`ID_STATEMENT_QUALIFIER`) REFERENCES `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (`ID_STATEMENT_QUALIFIER`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL,
  `AMOUNT` decimal(30,10) DEFAULT NULL,
  `UNIT_ID_WIKIDATA` varchar(50) DEFAULT NULL,
  `LOWER_BOUND` decimal(30,10) DEFAULT NULL,
  `UPPER_BOUND` decimal(30,10) DEFAULT NULL,
  `AMOUNT_NORMALIZED` decimal(30,10) DEFAULT NULL,
  `DISPLAY_VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUALIFIER_QUANTITY_VALUE_PARENT` FOREIGN KEY (`ID_STATEMENT_QUALIFIER`) REFERENCES `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (`ID_STATEMENT_QUALIFIER`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUALIFIER_STRING_VALUE` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL,
  `VALUE_STRING` longtext NOT NULL,
  `VALUE_STRING_NORMALIZED` longtext DEFAULT NULL,
  `LANG_CODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  KEY `IDX_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE_LANG_CODE` (`LANG_CODE`),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUALIFIER_STRING_VALUE_PARENT` FOREIGN KEY (`ID_STATEMENT_QUALIFIER`) REFERENCES `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (`ID_STATEMENT_QUALIFIER`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUALIFIER_TIME_VALUE` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL,
  `RAW_TIME_VALUE` varchar(100) NOT NULL,
  `PRECISION_CODE` int(11) DEFAULT NULL,
  `TIMEZONE_OFFSET` int(11) DEFAULT NULL,
  `CALENDAR_MODEL` varchar(255) DEFAULT NULL,
  `DATE_START` date DEFAULT NULL,
  `DATE_END` date DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUAL_TIME_VALUE_PARENT` FOREIGN KEY (`ID_STATEMENT_QUALIFIER`) REFERENCES `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (`ID_STATEMENT_QUALIFIER`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_QUANTITY_VALUE` (
  `ID_STATEMENT` bigint(20) NOT NULL,
  `AMOUNT` decimal(30,10) DEFAULT NULL,
  `UNIT_ID_WIKIDATA` varchar(50) DEFAULT NULL,
  `LOWER_BOUND` decimal(30,10) DEFAULT NULL,
  `UPPER_BOUND` decimal(30,10) DEFAULT NULL,
  `AMOUNT_NORMALIZED` decimal(30,10) DEFAULT NULL,
  `DISPLAY_VALUE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_QUANTITY_VALUE_AMOUNT` (`AMOUNT`),
  KEY `IDX_T_WC_WIKIDATA_QUANTITY_VALUE_UNIT` (`UNIT_ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_QUANTITY_VALUE_AMOUNT_NORMALIZED` (`AMOUNT_NORMALIZED`),
  CONSTRAINT `FK_T_WC_WIKIDATA_QUANTITY_VALUE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER BI_T_WC_WIKIDATA_QUANTITY_VALUE BEFORE INSERT ON T_WC_WIKIDATA_QUANTITY_VALUE
FOR EACH ROW
BEGIN
  DECLARE v_value_type VARCHAR(50);
  SELECT VALUE_TYPE INTO v_value_type FROM T_WC_WIKIDATA_STATEMENT WHERE ID_STATEMENT=NEW.ID_STATEMENT LIMIT 1;
  IF v_value_type IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='QUANTITY_VALUE: parent statement not found'; END IF;
  IF v_value_type <> 'quantity' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='QUANTITY_VALUE: parent VALUE_TYPE must be quantity'; END IF;
  IF EXISTS (SELECT 1 FROM T_WC_WIKIDATA_ITEM_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_STRING_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_MEDIA_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_TIME_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT)
  THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='QUANTITY_VALUE: statement already exists in another child table'; END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_SERIE` (
  `ID_ROW` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `LABEL_EN` varchar(500) DEFAULT NULL,
  `DESCRIPTION_EN` text DEFAULT NULL,
  `LABELS_JSON` longtext DEFAULT NULL,
  `DESCRIPTIONS_JSON` longtext DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`ID_ROW`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_SERIE_ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_SERIE_LABEL_EN` (`LABEL_EN`(255)),
  KEY `IDX_T_WC_WIKIDATA_SERIE_DELETED` (`DELETED`)
) ENGINE=InnoDB AUTO_INCREMENT=266237 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_SERIE_V1` (
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `ID_SERIE` int(11) NOT NULL,
  `TITLE` varchar(250) DEFAULT NULL,
  `DAT_START` date DEFAULT NULL,
  `DAT_END` date DEFAULT NULL,
  `ID_IMDB` varchar(20) DEFAULT NULL,
  `ALIASES` mediumtext DEFAULT NULL,
  `DELETED` int(5) DEFAULT NULL,
  `DISPLAY_ORDER` int(5) DEFAULT NULL,
  `ID_CREATOR` int(5) DEFAULT NULL,
  `DAT_CREAT` date DEFAULT NULL,
  `ID_OWNER` int(5) DEFAULT NULL,
  `TIM_UPDATED` datetime DEFAULT NULL,
  `ID_USER_UPDATED` int(5) DEFAULT NULL,
  `CRAWLER_VERSION` int(5) DEFAULT NULL,
  `PLEX_MEDIA_KEY` varchar(50) DEFAULT NULL,
  `ID_CRITERION` int(11) DEFAULT NULL,
  `ID_CRITERION_SPINE` int(11) DEFAULT NULL,
  `INSTANCE_OF` varchar(50) DEFAULT NULL,
  `WIKIPEDIA_POSTER_PATH` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`ID_WIKIDATA`),
  KEY `DELETED` (`DELETED`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `ID_OWNER` (`ID_OWNER`),
  KEY `ID_CREATOR` (`ID_CREATOR`),
  KEY `ID_USER_UPDATED` (`ID_USER_UPDATED`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `ID_IMDB` (`ID_IMDB`),
  KEY `TITLE` (`TITLE`),
  KEY `DAT_RELEASE` (`DAT_START`),
  KEY `CRAWLER_VERSION` (`CRAWLER_VERSION`),
  KEY `ID_SERIE` (`ID_SERIE`),
  KEY `ID_CRITERION` (`ID_CRITERION`),
  KEY `ID_CRITERION_SPINE` (`ID_CRITERION_SPINE`),
  KEY `PLEX_MEDIA_KEY` (`PLEX_MEDIA_KEY`),
  KEY `INSTANCE_OF` (`INSTANCE_OF`),
  KEY `DAT_END` (`DAT_END`),
  KEY `WIKIPEDIA_POSTER_PATH` (`WIKIPEDIA_POSTER_PATH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_STATEMENT` (
  `ID_STATEMENT` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_WIKIDATA` varchar(50) NOT NULL,
  `ID_PROPERTY` varchar(50) NOT NULL,
  `STATEMENT_GUID` varchar(255) DEFAULT NULL,
  `STATEMENT_HASH` varchar(255) DEFAULT NULL,
  `VALUE_TYPE` enum('item','string','external_id','media','time','quantity') NOT NULL,
  `WIKIDATA_DATATYPE` varchar(100) DEFAULT NULL,
  `RANK` enum('preferred','normal','deprecated') DEFAULT NULL,
  `IS_BEST_VALUE` tinyint(1) DEFAULT NULL,
  `DISPLAY_ORDER` int(11) DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `ID_CREATOR` bigint(20) DEFAULT NULL,
  `ID_OWNER` bigint(20) DEFAULT NULL,
  `ID_USER_UPDATED` bigint(20) DEFAULT NULL,
  `IMPORT_SOURCE` varchar(100) DEFAULT NULL,
  `IMPORT_BATCH_ID` varchar(100) DEFAULT NULL,
  `LAST_SYNC_AT` datetime DEFAULT NULL,
  `IS_VALID` tinyint(1) DEFAULT NULL,
  `VALIDATION_ERROR` text DEFAULT NULL,
  `RAW_VALUE_TEXT` text DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_STATEMENT_GUID` (`STATEMENT_GUID`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_STATEMENT_HASH` (`STATEMENT_HASH`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_ID_WIKIDATA` (`ID_WIKIDATA`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_ID_PROPERTY` (`ID_PROPERTY`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_VALUE_TYPE` (`VALUE_TYPE`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_RANK` (`RANK`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_IMPORT_BATCH_ID` (`IMPORT_BATCH_ID`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_DELETED` (`DELETED`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_WIKIDATA_PROPERTY` (`ID_WIKIDATA`,`ID_PROPERTY`),
  KEY `IDX_T_WC_WIKIDATA_STATEMENT_WIKIDATA_VALUE_TYPE` (`ID_WIKIDATA`,`VALUE_TYPE`),
  CONSTRAINT `FK_T_WC_WIKIDATA_STATEMENT_PROPERTY_METADATA` FOREIGN KEY (`ID_PROPERTY`) REFERENCES `T_WC_WIKIDATA_PROPERTY_METADATA` (`ID_PROPERTY`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=28049832 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_STATEMENT_QUALIFIER` (
  `ID_STATEMENT_QUALIFIER` bigint(20) NOT NULL AUTO_INCREMENT,
  `ID_STATEMENT` bigint(20) NOT NULL,
  `ID_QUALIFIER_PROPERTY` varchar(50) NOT NULL,
  `QUALIFIER_HASH` varchar(255) DEFAULT NULL,
  `VALUE_TYPE` enum('item','string','external_id','media','time','quantity') NOT NULL,
  `WIKIDATA_DATATYPE` varchar(100) DEFAULT NULL,
  `DISPLAY_ORDER` int(11) DEFAULT NULL,
  `DELETED` tinyint(1) DEFAULT 0,
  `DAT_CREAT` datetime DEFAULT current_timestamp(),
  `TIM_UPDATED` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `IMPORT_SOURCE` varchar(100) DEFAULT NULL,
  `IMPORT_BATCH_ID` varchar(100) DEFAULT NULL,
  `LAST_SYNC_AT` datetime DEFAULT NULL,
  `IS_VALID` tinyint(1) DEFAULT NULL,
  `VALIDATION_ERROR` text DEFAULT NULL,
  `RAW_VALUE_TEXT` text DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT_QUALIFIER`),
  UNIQUE KEY `UK_T_WC_WIKIDATA_STMT_QUALIFIER_HASH` (`QUALIFIER_HASH`),
  KEY `IDX_T_WC_WIKIDATA_STMT_QUALIFIER_STATEMENT` (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_STMT_QUALIFIER_PROPERTY` (`ID_QUALIFIER_PROPERTY`),
  KEY `IDX_T_WC_WIKIDATA_STMT_QUALIFIER_VALUE_TYPE` (`VALUE_TYPE`),
  KEY `IDX_T_WC_WIKIDATA_STMT_QUALIFIER_BATCH` (`IMPORT_BATCH_ID`),
  KEY `WIKIDATA_DATATYPE` (`WIKIDATA_DATATYPE`),
  KEY `DISPLAY_ORDER` (`DISPLAY_ORDER`),
  KEY `DELETED` (`DELETED`),
  KEY `DAT_CREAT` (`DAT_CREAT`),
  KEY `TIM_UPDATED` (`TIM_UPDATED`),
  KEY `IMPORT_SOURCE` (`IMPORT_SOURCE`),
  CONSTRAINT `FK_T_WC_WIKIDATA_STMT_QUALIFIER_PROPERTY_METADATA` FOREIGN KEY (`ID_QUALIFIER_PROPERTY`) REFERENCES `T_WC_WIKIDATA_PROPERTY_METADATA` (`ID_PROPERTY`) ON UPDATE CASCADE,
  CONSTRAINT `FK_T_WC_WIKIDATA_STMT_QUALIFIER_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_STRING_VALUE` (
  `ID_STATEMENT` bigint(20) NOT NULL,
  `VALUE_STRING` longtext NOT NULL,
  `VALUE_STRING_NORMALIZED` longtext DEFAULT NULL,
  `LANG_CODE` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_STRING_VALUE_LANG_CODE` (`LANG_CODE`),
  CONSTRAINT `FK_T_WC_WIKIDATA_STRING_VALUE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER BI_T_WC_WIKIDATA_STRING_VALUE BEFORE INSERT ON T_WC_WIKIDATA_STRING_VALUE
FOR EACH ROW
BEGIN
  DECLARE v_value_type VARCHAR(50);
  SELECT VALUE_TYPE INTO v_value_type FROM T_WC_WIKIDATA_STATEMENT WHERE ID_STATEMENT=NEW.ID_STATEMENT LIMIT 1;
  IF v_value_type IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STRING_VALUE: parent statement not found'; END IF;
  IF v_value_type <> 'string' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STRING_VALUE: parent VALUE_TYPE must be string'; END IF;
  IF EXISTS (SELECT 1 FROM T_WC_WIKIDATA_ITEM_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_MEDIA_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_TIME_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_QUANTITY_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT)
  THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='STRING_VALUE: statement already exists in another child table'; END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `T_WC_WIKIDATA_TIME_VALUE` (
  `ID_STATEMENT` bigint(20) NOT NULL,
  `RAW_TIME_VALUE` varchar(100) DEFAULT NULL,
  `TIME_PRECISION` int(11) DEFAULT NULL,
  `CALENDAR_MODEL` varchar(255) DEFAULT NULL,
  `TIMEZONE_OFFSET` int(11) DEFAULT NULL,
  `YEAR_VALUE` int(11) DEFAULT NULL,
  `MONTH_VALUE` int(11) DEFAULT NULL,
  `DAY_VALUE` int(11) DEFAULT NULL,
  `DATE_START` date DEFAULT NULL,
  `DATE_END` date DEFAULT NULL,
  PRIMARY KEY (`ID_STATEMENT`),
  KEY `IDX_T_WC_WIKIDATA_TIME_VALUE_YEAR` (`YEAR_VALUE`),
  KEY `IDX_T_WC_WIKIDATA_TIME_VALUE_MONTH` (`MONTH_VALUE`),
  KEY `IDX_T_WC_WIKIDATA_TIME_VALUE_DAY` (`DAY_VALUE`),
  KEY `IDX_T_WC_WIKIDATA_TIME_VALUE_DATE_START` (`DATE_START`),
  KEY `IDX_T_WC_WIKIDATA_TIME_VALUE_DATE_END` (`DATE_END`),
  KEY `IDX_T_WC_WIKIDATA_TIME_VALUE_PRECISION` (`TIME_PRECISION`),
  CONSTRAINT `FK_T_WC_WIKIDATA_TIME_VALUE_STATEMENT` FOREIGN KEY (`ID_STATEMENT`) REFERENCES `T_WC_WIKIDATA_STATEMENT` (`ID_STATEMENT`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!50003 SET @saved_cs_client      = @@character_set_client */ ;
/*!50003 SET @saved_cs_results     = @@character_set_results */ ;
/*!50003 SET @saved_col_connection = @@collation_connection */ ;
/*!50003 SET character_set_client  = utf8mb4 */ ;
/*!50003 SET character_set_results = utf8mb4 */ ;
/*!50003 SET collation_connection  = utf8mb4_general_ci */ ;
/*!50003 SET @saved_sql_mode       = @@sql_mode */ ;
/*!50003 SET sql_mode              = 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ ;
DELIMITER ;;
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`%`*/ /*!50003 TRIGGER BI_T_WC_WIKIDATA_TIME_VALUE BEFORE INSERT ON T_WC_WIKIDATA_TIME_VALUE
FOR EACH ROW
BEGIN
  DECLARE v_value_type VARCHAR(50);
  SELECT VALUE_TYPE INTO v_value_type FROM T_WC_WIKIDATA_STATEMENT WHERE ID_STATEMENT=NEW.ID_STATEMENT LIMIT 1;
  IF v_value_type IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='TIME_VALUE: parent statement not found'; END IF;
  IF v_value_type <> 'time' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='TIME_VALUE: parent VALUE_TYPE must be time'; END IF;
  IF EXISTS (SELECT 1 FROM T_WC_WIKIDATA_ITEM_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_STRING_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_EXTERNAL_ID_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_MEDIA_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT) OR
     EXISTS (SELECT 1 FROM T_WC_WIKIDATA_QUANTITY_VALUE WHERE ID_STATEMENT=NEW.ID_STATEMENT)
  THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='TIME_VALUE: statement already exists in another child table'; END IF;
END */;;
DELIMITER ;
/*!50003 SET sql_mode              = @saved_sql_mode */ ;
/*!50003 SET character_set_client  = @saved_cs_client */ ;
/*!50003 SET character_set_results = @saved_cs_results */ ;
/*!50003 SET collation_connection  = @saved_col_connection */ ;
